<?php

namespace Database\Seeders;

use App\Models\State;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $state = State::factory(10)->create();
        $states = [
            ['id' => '1', 'country_id' => '101', 'name' => 'andaman and nicobar islands'],
            ['id' => '2', 'country_id' => '101', 'name' => 'andhra pradesh'],
            ['id' => '3', 'country_id' => '101', 'name' => 'arunachal pradesh'],
            ['id' => '4', 'country_id' => '101', 'name' => 'assam'],
            ['id' => '5', 'country_id' => '101', 'name' => 'bihar'],
            ['id' => '6', 'country_id' => '101', 'name' => 'chandigarh'],
            ['id' => '7', 'country_id' => '101', 'name' => 'chhattisgarh'],
            ['id' => '8', 'country_id' => '101', 'name' => 'dadra and nagar haveli'],
            ['id' => '9', 'country_id' => '101', 'name' => 'daman and diu'],
            ['id' => '10', 'country_id' => '101', 'name' => 'delhi'],
            ['id' => '11', 'country_id' => '101', 'name' => 'goa'],
            ['id' => '12', 'country_id' => '101', 'name' => 'gujarat'],
            ['id' => '13', 'country_id' => '101', 'name' => 'haryana'],
            ['id' => '14', 'country_id' => '101', 'name' => 'himachal pradesh'],
            ['id' => '15', 'country_id' => '101', 'name' => 'jammu and kashmir'],
            ['id' => '16', 'country_id' => '101', 'name' => 'jharkhand'],
            ['id' => '17', 'country_id' => '101', 'name' => 'karnataka'],
            ['id' => '18', 'country_id' => '101', 'name' => 'kenmore'],
            ['id' => '19', 'country_id' => '101', 'name' => 'kerala'],
            ['id' => '20', 'country_id' => '101', 'name' => 'lakshadweep'],
            ['id' => '21', 'country_id' => '101', 'name' => 'madhya pradesh'],
            ['id' => '22', 'country_id' => '101', 'name' => 'maharashtra'],
            ['id' => '23', 'country_id' => '101', 'name' => 'manipur'],
            ['id' => '24', 'country_id' => '101', 'name' => 'meghalaya'],
            ['id' => '25', 'country_id' => '101', 'name' => 'mizoram'],
            ['id' => '26', 'country_id' => '101', 'name' => 'nagaland'],
            ['id' => '27', 'country_id' => '101', 'name' => 'narora'],
            ['id' => '28', 'country_id' => '101', 'name' => 'natwar'],
            ['id' => '29', 'country_id' => '101', 'name' => 'odisha'],
            ['id' => '30', 'country_id' => '101', 'name' => 'paschim medinipur'],
            ['id' => '31', 'country_id' => '101', 'name' => 'pondicherry'],
            ['id' => '32', 'country_id' => '101', 'name' => 'punjab'],
            ['id' => '33', 'country_id' => '101', 'name' => 'rajasthan'],
            ['id' => '34', 'country_id' => '101', 'name' => 'sikkim'],
            ['id' => '35', 'country_id' => '101', 'name' => 'tamil nadu'],
            ['id' => '36', 'country_id' => '101', 'name' => 'telangana'],
            ['id' => '37', 'country_id' => '101', 'name' => 'tripura'],
            ['id' => '38', 'country_id' => '101', 'name' => 'uttar pradesh'],
            ['id' => '39', 'country_id' => '101', 'name' => 'uttarakhand'],
            ['id' => '40', 'country_id' => '101', 'name' => 'vaishali'],
            ['id' => '41', 'country_id' => '101', 'name' => 'west bengal'],
            ['id' => '512', 'country_id' => '30', 'name' => 'acre'],
            ['id' => '513', 'country_id' => '30', 'name' => 'alagoas'],
            ['id' => '514', 'country_id' => '30', 'name' => 'amapa'],
            ['id' => '515', 'country_id' => '30', 'name' => 'amazonas'],
            ['id' => '516', 'country_id' => '30', 'name' => 'bahia'],
            ['id' => '517', 'country_id' => '30', 'name' => 'ceara'],
            ['id' => '518', 'country_id' => '30', 'name' => 'distrito federal'],
            ['id' => '519', 'country_id' => '30', 'name' => 'espirito santo'],
            ['id' => '520', 'country_id' => '30', 'name' => 'estado de sao paulo'],
            ['id' => '521', 'country_id' => '30', 'name' => 'goias'],
            ['id' => '522', 'country_id' => '30', 'name' => 'maranhao'],
            ['id' => '523', 'country_id' => '30', 'name' => 'mato grosso'],
            ['id' => '524', 'country_id' => '30', 'name' => 'mato grosso do sul'],
            ['id' => '525', 'country_id' => '30', 'name' => 'minas gerais'],
            ['id' => '526', 'country_id' => '30', 'name' => 'para'],
            ['id' => '527', 'country_id' => '30', 'name' => 'paraiba'],
            ['id' => '528', 'country_id' => '30', 'name' => 'parana'],
            ['id' => '529', 'country_id' => '30', 'name' => 'pernambuco'],
            ['id' => '530', 'country_id' => '30', 'name' => 'piaui'],
            ['id' => '531', 'country_id' => '30', 'name' => 'rio grande do norte'],
            ['id' => '532', 'country_id' => '30', 'name' => 'rio grande do sul'],
            ['id' => '533', 'country_id' => '30', 'name' => 'rio de janeiro'],
            ['id' => '534', 'country_id' => '30', 'name' => 'rondonia'],
            ['id' => '535', 'country_id' => '30', 'name' => 'roraima'],
            ['id' => '536', 'country_id' => '30', 'name' => 'santa catarina'],
            ['id' => '537', 'country_id' => '30', 'name' => 'sao paulo'],
            ['id' => '538', 'country_id' => '30', 'name' => 'sergipe'],
            ['id' => '539', 'country_id' => '30', 'name' => 'tocantins'],
            ['id' => '663', 'country_id' => '38', 'name' => 'alberta'],
            ['id' => '664', 'country_id' => '38', 'name' => 'british columbia'],
            ['id' => '665', 'country_id' => '38', 'name' => 'manitoba'],
            ['id' => '666', 'country_id' => '38', 'name' => 'new brunswick'],
            ['id' => '667', 'country_id' => '38', 'name' => 'newfoundland and labrador'],
            ['id' => '668', 'country_id' => '38', 'name' => 'northwest territories'],
            ['id' => '669', 'country_id' => '38', 'name' => 'nova scotia'],
            ['id' => '670', 'country_id' => '38', 'name' => 'nunavut'],
            ['id' => '671', 'country_id' => '38', 'name' => 'ontario'],
            ['id' => '672', 'country_id' => '38', 'name' => 'prince edward island'],
            ['id' => '673', 'country_id' => '38', 'name' => 'quebec'],
            ['id' => '674', 'country_id' => '38', 'name' => 'saskatchewan'],
            ['id' => '675', 'country_id' => '38', 'name' => 'yukon'],
            ['id' => '731', 'country_id' => '44', 'name' => 'anhui'],
            ['id' => '732', 'country_id' => '44', 'name' => 'anhui province'],
            ['id' => '733', 'country_id' => '44', 'name' => 'anhui sheng'],
            ['id' => '734', 'country_id' => '44', 'name' => 'aomen'],
            ['id' => '735', 'country_id' => '44', 'name' => 'beijing'],
            ['id' => '736', 'country_id' => '44', 'name' => 'beijing shi'],
            ['id' => '737', 'country_id' => '44', 'name' => 'chongqing'],
            ['id' => '738', 'country_id' => '44', 'name' => 'fujian'],
            ['id' => '739', 'country_id' => '44', 'name' => 'fujian sheng'],
            ['id' => '740', 'country_id' => '44', 'name' => 'gansu'],
            ['id' => '741', 'country_id' => '44', 'name' => 'guangdong'],
            ['id' => '742', 'country_id' => '44', 'name' => 'guangdong sheng'],
            ['id' => '743', 'country_id' => '44', 'name' => 'guangxi'],
            ['id' => '744', 'country_id' => '44', 'name' => 'guizhou'],
            ['id' => '745', 'country_id' => '44', 'name' => 'hainan'],
            ['id' => '746', 'country_id' => '44', 'name' => 'hebei'],
            ['id' => '747', 'country_id' => '44', 'name' => 'heilongjiang'],
            ['id' => '748', 'country_id' => '44', 'name' => 'henan'],
            ['id' => '749', 'country_id' => '44', 'name' => 'hubei'],
            ['id' => '750', 'country_id' => '44', 'name' => 'hunan'],
            ['id' => '751', 'country_id' => '44', 'name' => 'jiangsu'],
            ['id' => '752', 'country_id' => '44', 'name' => 'jiangsu sheng'],
            ['id' => '753', 'country_id' => '44', 'name' => 'jiangxi'],
            ['id' => '754', 'country_id' => '44', 'name' => 'jilin'],
            ['id' => '755', 'country_id' => '44', 'name' => 'liaoning'],
            ['id' => '756', 'country_id' => '44', 'name' => 'liaoning sheng'],
            ['id' => '757', 'country_id' => '44', 'name' => 'nei monggol'],
            ['id' => '758', 'country_id' => '44', 'name' => 'ningxia hui'],
            ['id' => '759', 'country_id' => '44', 'name' => 'qinghai'],
            ['id' => '760', 'country_id' => '44', 'name' => 'shaanxi'],
            ['id' => '761', 'country_id' => '44', 'name' => 'shandong'],
            ['id' => '762', 'country_id' => '44', 'name' => 'shandong sheng'],
            ['id' => '763', 'country_id' => '44', 'name' => 'shanghai'],
            ['id' => '764', 'country_id' => '44', 'name' => 'shanxi'],
            ['id' => '765', 'country_id' => '44', 'name' => 'sichuan'],
            ['id' => '766', 'country_id' => '44', 'name' => 'tianjin'],
            ['id' => '767', 'country_id' => '44', 'name' => 'xianggang'],
            ['id' => '768', 'country_id' => '44', 'name' => 'xinjiang'],
            ['id' => '769', 'country_id' => '44', 'name' => 'xizang'],
            ['id' => '770', 'country_id' => '44', 'name' => 'yunnan'],
            ['id' => '771', 'country_id' => '44', 'name' => 'zhejiang'],
            ['id' => '772', 'country_id' => '44', 'name' => 'zhejiang sheng'],
            ['id' => '1181', 'country_id' => '75', 'name' => 'ain'],
            ['id' => '1182', 'country_id' => '75', 'name' => 'aisne'],
            ['id' => '1183', 'country_id' => '75', 'name' => 'albi le sequestre'],
            ['id' => '1184', 'country_id' => '75', 'name' => 'allier'],
            ['id' => '1185', 'country_id' => '75', 'name' => 'alpes-cote dazur'],
            ['id' => '1186', 'country_id' => '75', 'name' => 'alpes-maritimes'],
            ['id' => '1187', 'country_id' => '75', 'name' => 'alpes-de-haute-provence'],
            ['id' => '1188', 'country_id' => '75', 'name' => 'alsace'],
            ['id' => '1189', 'country_id' => '75', 'name' => 'aquitaine'],
            ['id' => '1190', 'country_id' => '75', 'name' => 'ardeche'],
            ['id' => '1191', 'country_id' => '75', 'name' => 'ardennes'],
            ['id' => '1192', 'country_id' => '75', 'name' => 'ariege'],
            ['id' => '1193', 'country_id' => '75', 'name' => 'aube'],
            ['id' => '1194', 'country_id' => '75', 'name' => 'aude'],
            ['id' => '1195', 'country_id' => '75', 'name' => 'auvergne'],
            ['id' => '1196', 'country_id' => '75', 'name' => 'aveyron'],
            ['id' => '1197', 'country_id' => '75', 'name' => 'bas-rhin'],
            ['id' => '1198', 'country_id' => '75', 'name' => 'basse-normandie'],
            ['id' => '1199', 'country_id' => '75', 'name' => 'bouches-du-rhone'],
            ['id' => '1200', 'country_id' => '75', 'name' => 'bourgogne'],
            ['id' => '1201', 'country_id' => '75', 'name' => 'bretagne'],
            ['id' => '1202', 'country_id' => '75', 'name' => 'brittany'],
            ['id' => '1203', 'country_id' => '75', 'name' => 'burgundy'],
            ['id' => '1204', 'country_id' => '75', 'name' => 'calvados'],
            ['id' => '1205', 'country_id' => '75', 'name' => 'cantal'],
            ['id' => '1206', 'country_id' => '75', 'name' => 'cedex'],
            ['id' => '1207', 'country_id' => '75', 'name' => 'centre'],
            ['id' => '1208', 'country_id' => '75', 'name' => 'charente'],
            ['id' => '1209', 'country_id' => '75', 'name' => 'charente-maritime'],
            ['id' => '1210', 'country_id' => '75', 'name' => 'cher'],
            ['id' => '1211', 'country_id' => '75', 'name' => 'correze'],
            ['id' => '1212', 'country_id' => '75', 'name' => 'corse-du-sud'],
            ['id' => '1213', 'country_id' => '75', 'name' => 'cote-d\'or'],
            ['id' => '1214', 'country_id' => '75', 'name' => 'cotes-d\'armor'],
            ['id' => '1215', 'country_id' => '75', 'name' => 'creuse'],
            ['id' => '1216', 'country_id' => '75', 'name' => 'crolles'],
            ['id' => '1217', 'country_id' => '75', 'name' => 'deux-sevres'],
            ['id' => '1218', 'country_id' => '75', 'name' => 'dordogne'],
            ['id' => '1219', 'country_id' => '75', 'name' => 'doubs'],
            ['id' => '1220', 'country_id' => '75', 'name' => 'drome'],
            ['id' => '1221', 'country_id' => '75', 'name' => 'essonne'],
            ['id' => '1222', 'country_id' => '75', 'name' => 'eure'],
            ['id' => '1223', 'country_id' => '75', 'name' => 'eure-et-loir'],
            ['id' => '1224', 'country_id' => '75', 'name' => 'feucherolles'],
            ['id' => '1225', 'country_id' => '75', 'name' => 'finistere'],
            ['id' => '1226', 'country_id' => '75', 'name' => 'franche-comte'],
            ['id' => '1227', 'country_id' => '75', 'name' => 'gard'],
            ['id' => '1228', 'country_id' => '75', 'name' => 'gers'],
            ['id' => '1229', 'country_id' => '75', 'name' => 'gironde'],
            ['id' => '1230', 'country_id' => '75', 'name' => 'haut-rhin'],
            ['id' => '1231', 'country_id' => '75', 'name' => 'haute-corse'],
            ['id' => '1232', 'country_id' => '75', 'name' => 'haute-garonne'],
            ['id' => '1233', 'country_id' => '75', 'name' => 'haute-loire'],
            ['id' => '1234', 'country_id' => '75', 'name' => 'haute-marne'],
            ['id' => '1235', 'country_id' => '75', 'name' => 'haute-saone'],
            ['id' => '1236', 'country_id' => '75', 'name' => 'haute-savoie'],
            ['id' => '1237', 'country_id' => '75', 'name' => 'haute-vienne'],
            ['id' => '1238', 'country_id' => '75', 'name' => 'hautes-alpes'],
            ['id' => '1239', 'country_id' => '75', 'name' => 'hautes-pyrenees'],
            ['id' => '1240', 'country_id' => '75', 'name' => 'hauts-de-seine'],
            ['id' => '1241', 'country_id' => '75', 'name' => 'herault'],
            ['id' => '1242', 'country_id' => '75', 'name' => 'ile-de-france'],
            ['id' => '1243', 'country_id' => '75', 'name' => 'ille-et-vilaine'],
            ['id' => '1244', 'country_id' => '75', 'name' => 'indre'],
            ['id' => '1245', 'country_id' => '75', 'name' => 'indre-et-loire'],
            ['id' => '1246', 'country_id' => '75', 'name' => 'isere'],
            ['id' => '1247', 'country_id' => '75', 'name' => 'jura'],
            ['id' => '1248', 'country_id' => '75', 'name' => 'klagenfurt'],
            ['id' => '1249', 'country_id' => '75', 'name' => 'landes'],
            ['id' => '1250', 'country_id' => '75', 'name' => 'languedoc-roussillon'],
            ['id' => '1251', 'country_id' => '75', 'name' => 'larcay'],
            ['id' => '1252', 'country_id' => '75', 'name' => 'le castellet'],
            ['id' => '1253', 'country_id' => '75', 'name' => 'le creusot'],
            ['id' => '1254', 'country_id' => '75', 'name' => 'limousin'],
            ['id' => '1255', 'country_id' => '75', 'name' => 'loir-et-cher'],
            ['id' => '1256', 'country_id' => '75', 'name' => 'loire'],
            ['id' => '1257', 'country_id' => '75', 'name' => 'loire-atlantique'],
            ['id' => '1258', 'country_id' => '75', 'name' => 'loiret'],
            ['id' => '1259', 'country_id' => '75', 'name' => 'lorraine'],
            ['id' => '1260', 'country_id' => '75', 'name' => 'lot'],
            ['id' => '1261', 'country_id' => '75', 'name' => 'lot-et-garonne'],
            ['id' => '1262', 'country_id' => '75', 'name' => 'lower normandy'],
            ['id' => '1263', 'country_id' => '75', 'name' => 'lozere'],
            ['id' => '1264', 'country_id' => '75', 'name' => 'maine-et-loire'],
            ['id' => '1265', 'country_id' => '75', 'name' => 'manche'],
            ['id' => '1266', 'country_id' => '75', 'name' => 'marne'],
            ['id' => '1267', 'country_id' => '75', 'name' => 'mayenne'],
            ['id' => '1268', 'country_id' => '75', 'name' => 'meurthe-et-moselle'],
            ['id' => '1269', 'country_id' => '75', 'name' => 'meuse'],
            ['id' => '1270', 'country_id' => '75', 'name' => 'midi-pyrenees'],
            ['id' => '1271', 'country_id' => '75', 'name' => 'morbihan'],
            ['id' => '1272', 'country_id' => '75', 'name' => 'moselle'],
            ['id' => '1273', 'country_id' => '75', 'name' => 'nievre'],
            ['id' => '1274', 'country_id' => '75', 'name' => 'nord'],
            ['id' => '1275', 'country_id' => '75', 'name' => 'nord-pas-de-calais'],
            ['id' => '1276', 'country_id' => '75', 'name' => 'oise'],
            ['id' => '1277', 'country_id' => '75', 'name' => 'orne'],
            ['id' => '1278', 'country_id' => '75', 'name' => 'paris'],
            ['id' => '1279', 'country_id' => '75', 'name' => 'pas-de-calais'],
            ['id' => '1280', 'country_id' => '75', 'name' => 'pays de la loire'],
            ['id' => '1281', 'country_id' => '75', 'name' => 'pays-de-la-loire'],
            ['id' => '1282', 'country_id' => '75', 'name' => 'picardy'],
            ['id' => '1283', 'country_id' => '75', 'name' => 'puy-de-dome'],
            ['id' => '1284', 'country_id' => '75', 'name' => 'pyrenees-atlantiques'],
            ['id' => '1285', 'country_id' => '75', 'name' => 'pyrenees-orientales'],
            ['id' => '1286', 'country_id' => '75', 'name' => 'quelmes'],
            ['id' => '1287', 'country_id' => '75', 'name' => 'rhone'],
            ['id' => '1288', 'country_id' => '75', 'name' => 'rhone-alpes'],
            ['id' => '1289', 'country_id' => '75', 'name' => 'saint ouen'],
            ['id' => '1290', 'country_id' => '75', 'name' => 'saint viatre'],
            ['id' => '1291', 'country_id' => '75', 'name' => 'saone-et-loire'],
            ['id' => '1292', 'country_id' => '75', 'name' => 'sarthe'],
            ['id' => '1293', 'country_id' => '75', 'name' => 'savoie'],
            ['id' => '1294', 'country_id' => '75', 'name' => 'seine-maritime'],
            ['id' => '1295', 'country_id' => '75', 'name' => 'seine-saint-denis'],
            ['id' => '1296', 'country_id' => '75', 'name' => 'seine-et-marne'],
            ['id' => '1297', 'country_id' => '75', 'name' => 'somme'],
            ['id' => '1298', 'country_id' => '75', 'name' => 'sophia antipolis'],
            ['id' => '1299', 'country_id' => '75', 'name' => 'souvans'],
            ['id' => '1300', 'country_id' => '75', 'name' => 'tarn'],
            ['id' => '1301', 'country_id' => '75', 'name' => 'tarn-et-garonne'],
            ['id' => '1302', 'country_id' => '75', 'name' => 'territoire de belfort'],
            ['id' => '1303', 'country_id' => '75', 'name' => 'treignac'],
            ['id' => '1304', 'country_id' => '75', 'name' => 'upper normandy'],
            ['id' => '1305', 'country_id' => '75', 'name' => 'val-d\'oise'],
            ['id' => '1306', 'country_id' => '75', 'name' => 'val-de-marne'],
            ['id' => '1307', 'country_id' => '75', 'name' => 'var'],
            ['id' => '1308', 'country_id' => '75', 'name' => 'vaucluse'],
            ['id' => '1309', 'country_id' => '75', 'name' => 'vellise'],
            ['id' => '1310', 'country_id' => '75', 'name' => 'vendee'],
            ['id' => '1311', 'country_id' => '75', 'name' => 'vienne'],
            ['id' => '1312', 'country_id' => '75', 'name' => 'vosges'],
            ['id' => '1313', 'country_id' => '75', 'name' => 'yonne'],
            ['id' => '1314', 'country_id' => '75', 'name' => 'yvelines'],
            ['id' => '1354', 'country_id' => '82', 'name' => 'auvergne'],
            ['id' => '1355', 'country_id' => '82', 'name' => 'baden-wurttemberg'],
            ['id' => '1356', 'country_id' => '82', 'name' => 'bavaria'],
            ['id' => '1357', 'country_id' => '82', 'name' => 'bayern'],
            ['id' => '1358', 'country_id' => '82', 'name' => 'beilstein wurtt'],
            ['id' => '1359', 'country_id' => '82', 'name' => 'berlin'],
            ['id' => '1360', 'country_id' => '82', 'name' => 'brandenburg'],
            ['id' => '1361', 'country_id' => '82', 'name' => 'bremen'],
            ['id' => '1362', 'country_id' => '82', 'name' => 'dreisbach'],
            ['id' => '1363', 'country_id' => '82', 'name' => 'freistaat bayern'],
            ['id' => '1364', 'country_id' => '82', 'name' => 'hamburg'],
            ['id' => '1365', 'country_id' => '82', 'name' => 'hannover'],
            ['id' => '1366', 'country_id' => '82', 'name' => 'heroldstatt'],
            ['id' => '1367', 'country_id' => '82', 'name' => 'hessen'],
            ['id' => '1368', 'country_id' => '82', 'name' => 'kortenberg'],
            ['id' => '1369', 'country_id' => '82', 'name' => 'laasdorf'],
            ['id' => '1370', 'country_id' => '82', 'name' => 'land baden-wurttemberg'],
            ['id' => '1371', 'country_id' => '82', 'name' => 'land bayern'],
            ['id' => '1372', 'country_id' => '82', 'name' => 'land brandenburg'],
            ['id' => '1373', 'country_id' => '82', 'name' => 'land hessen'],
            ['id' => '1374', 'country_id' => '82', 'name' => 'land mecklenburg-vorpommern'],
            ['id' => '1375', 'country_id' => '82', 'name' => 'land nordrhein-westfalen'],
            ['id' => '1376', 'country_id' => '82', 'name' => 'land rheinland-pfalz'],
            ['id' => '1377', 'country_id' => '82', 'name' => 'land sachsen'],
            ['id' => '1378', 'country_id' => '82', 'name' => 'land sachsen-anhalt'],
            ['id' => '1379', 'country_id' => '82', 'name' => 'land thuringen'],
            ['id' => '1380', 'country_id' => '82', 'name' => 'lower saxony'],
            ['id' => '1381', 'country_id' => '82', 'name' => 'mecklenburg-vorpommern'],
            ['id' => '1382', 'country_id' => '82', 'name' => 'mulfingen'],
            ['id' => '1383', 'country_id' => '82', 'name' => 'munich'],
            ['id' => '1384', 'country_id' => '82', 'name' => 'neubeuern'],
            ['id' => '1385', 'country_id' => '82', 'name' => 'niedersachsen'],
            ['id' => '1386', 'country_id' => '82', 'name' => 'noord-holland'],
            ['id' => '1387', 'country_id' => '82', 'name' => 'nordrhein-westfalen'],
            ['id' => '1388', 'country_id' => '82', 'name' => 'north rhine-westphalia'],
            ['id' => '1389', 'country_id' => '82', 'name' => 'osterode'],
            ['id' => '1390', 'country_id' => '82', 'name' => 'rheinland-pfalz'],
            ['id' => '1391', 'country_id' => '82', 'name' => 'rhineland-palatinate'],
            ['id' => '1392', 'country_id' => '82', 'name' => 'saarland'],
            ['id' => '1393', 'country_id' => '82', 'name' => 'sachsen'],
            ['id' => '1394', 'country_id' => '82', 'name' => 'sachsen-anhalt'],
            ['id' => '1395', 'country_id' => '82', 'name' => 'saxony'],
            ['id' => '1396', 'country_id' => '82', 'name' => 'schleswig-holstein'],
            ['id' => '1397', 'country_id' => '82', 'name' => 'thuringia'],
            ['id' => '1398', 'country_id' => '82', 'name' => 'webling'],
            ['id' => '1399', 'country_id' => '82', 'name' => 'weinstrabe'],
            ['id' => '1400', 'country_id' => '82', 'name' => 'schlobborn'],
            ['id' => '1918', 'country_id' => '109', 'name' => 'aichi'],
            ['id' => '1919', 'country_id' => '109', 'name' => 'akita'],
            ['id' => '1920', 'country_id' => '109', 'name' => 'aomori'],
            ['id' => '1921', 'country_id' => '109', 'name' => 'chiba'],
            ['id' => '1922', 'country_id' => '109', 'name' => 'ehime'],
            ['id' => '1923', 'country_id' => '109', 'name' => 'fukui'],
            ['id' => '1924', 'country_id' => '109', 'name' => 'fukuoka'],
            ['id' => '1925', 'country_id' => '109', 'name' => 'fukushima'],
            ['id' => '1926', 'country_id' => '109', 'name' => 'gifu'],
            ['id' => '1927', 'country_id' => '109', 'name' => 'gumma'],
            ['id' => '1928', 'country_id' => '109', 'name' => 'hiroshima'],
            ['id' => '1929', 'country_id' => '109', 'name' => 'hokkaido'],
            ['id' => '1930', 'country_id' => '109', 'name' => 'hyogo'],
            ['id' => '1931', 'country_id' => '109', 'name' => 'ibaraki'],
            ['id' => '1932', 'country_id' => '109', 'name' => 'ishikawa'],
            ['id' => '1933', 'country_id' => '109', 'name' => 'iwate'],
            ['id' => '1934', 'country_id' => '109', 'name' => 'kagawa'],
            ['id' => '1935', 'country_id' => '109', 'name' => 'kagoshima'],
            ['id' => '1936', 'country_id' => '109', 'name' => 'kanagawa'],
            ['id' => '1937', 'country_id' => '109', 'name' => 'kanto'],
            ['id' => '1938', 'country_id' => '109', 'name' => 'kochi'],
            ['id' => '1939', 'country_id' => '109', 'name' => 'kumamoto'],
            ['id' => '1940', 'country_id' => '109', 'name' => 'kyoto'],
            ['id' => '1941', 'country_id' => '109', 'name' => 'mie'],
            ['id' => '1942', 'country_id' => '109', 'name' => 'miyagi'],
            ['id' => '1943', 'country_id' => '109', 'name' => 'miyazaki'],
            ['id' => '1944', 'country_id' => '109', 'name' => 'nagano'],
            ['id' => '1945', 'country_id' => '109', 'name' => 'nagasaki'],
            ['id' => '1946', 'country_id' => '109', 'name' => 'nara'],
            ['id' => '1947', 'country_id' => '109', 'name' => 'niigata'],
            ['id' => '1948', 'country_id' => '109', 'name' => 'oita'],
            ['id' => '1949', 'country_id' => '109', 'name' => 'okayama'],
            ['id' => '1950', 'country_id' => '109', 'name' => 'okinawa'],
            ['id' => '1951', 'country_id' => '109', 'name' => 'osaka'],
            ['id' => '1952', 'country_id' => '109', 'name' => 'saga'],
            ['id' => '1953', 'country_id' => '109', 'name' => 'saitama'],
            ['id' => '1954', 'country_id' => '109', 'name' => 'shiga'],
            ['id' => '1955', 'country_id' => '109', 'name' => 'shimane'],
            ['id' => '1956', 'country_id' => '109', 'name' => 'shizuoka'],
            ['id' => '1957', 'country_id' => '109', 'name' => 'tochigi'],
            ['id' => '1958', 'country_id' => '109', 'name' => 'tokushima'],
            ['id' => '1959', 'country_id' => '109', 'name' => 'tokyo'],
            ['id' => '1960', 'country_id' => '109', 'name' => 'tottori'],
            ['id' => '1961', 'country_id' => '109', 'name' => 'toyama'],
            ['id' => '1962', 'country_id' => '109', 'name' => 'wakayama'],
            ['id' => '1963', 'country_id' => '109', 'name' => 'yamagata'],
            ['id' => '1964', 'country_id' => '109', 'name' => 'yamaguchi'],
            ['id' => '1965', 'country_id' => '109', 'name' => 'yamanashi'],
            ['id' => '2427', 'country_id' => '142', 'name' => 'aguascalientes'],
            ['id' => '2428', 'country_id' => '142', 'name' => 'baja california'],
            ['id' => '2429', 'country_id' => '142', 'name' => 'baja california sur'],
            ['id' => '2430', 'country_id' => '142', 'name' => 'campeche'],
            ['id' => '2431', 'country_id' => '142', 'name' => 'chiapas'],
            ['id' => '2432', 'country_id' => '142', 'name' => 'chihuahua'],
            ['id' => '2433', 'country_id' => '142', 'name' => 'coahuila'],
            ['id' => '2434', 'country_id' => '142', 'name' => 'colima'],
            ['id' => '2435', 'country_id' => '142', 'name' => 'distrito federal'],
            ['id' => '2436', 'country_id' => '142', 'name' => 'durango'],
            ['id' => '2437', 'country_id' => '142', 'name' => 'estado de mexico'],
            ['id' => '2438', 'country_id' => '142', 'name' => 'guanajuato'],
            ['id' => '2439', 'country_id' => '142', 'name' => 'guerrero'],
            ['id' => '2440', 'country_id' => '142', 'name' => 'hidalgo'],
            ['id' => '2441', 'country_id' => '142', 'name' => 'jalisco'],
            ['id' => '2442', 'country_id' => '142', 'name' => 'mexico'],
            ['id' => '2443', 'country_id' => '142', 'name' => 'michoacan'],
            ['id' => '2444', 'country_id' => '142', 'name' => 'morelos'],
            ['id' => '2445', 'country_id' => '142', 'name' => 'nayarit'],
            ['id' => '2446', 'country_id' => '142', 'name' => 'nuevo leon'],
            ['id' => '2447', 'country_id' => '142', 'name' => 'oaxaca'],
            ['id' => '2448', 'country_id' => '142', 'name' => 'puebla'],
            ['id' => '2449', 'country_id' => '142', 'name' => 'queretaro'],
            ['id' => '2450', 'country_id' => '142', 'name' => 'quintana roo'],
            ['id' => '2451', 'country_id' => '142', 'name' => 'san luis potosi'],
            ['id' => '2452', 'country_id' => '142', 'name' => 'sinaloa'],
            ['id' => '2453', 'country_id' => '142', 'name' => 'sonora'],
            ['id' => '2454', 'country_id' => '142', 'name' => 'tabasco'],
            ['id' => '2455', 'country_id' => '142', 'name' => 'tamaulipas'],
            ['id' => '2456', 'country_id' => '142', 'name' => 'tlaxcala'],
            ['id' => '2457', 'country_id' => '142', 'name' => 'veracruz'],
            ['id' => '2458', 'country_id' => '142', 'name' => 'yucatan'],
            ['id' => '2459', 'country_id' => '142', 'name' => 'zacatecas'],
            ['id' => '2977', 'country_id' => '181', 'name' => 'adygeja'],
            ['id' => '2978', 'country_id' => '181', 'name' => 'aga'],
            ['id' => '2979', 'country_id' => '181', 'name' => 'alanija'],
            ['id' => '2980', 'country_id' => '181', 'name' => 'altaj'],
            ['id' => '2981', 'country_id' => '181', 'name' => 'amur'],
            ['id' => '2982', 'country_id' => '181', 'name' => 'arhangelsk'],
            ['id' => '2983', 'country_id' => '181', 'name' => 'astrahan'],
            ['id' => '2984', 'country_id' => '181', 'name' => 'bashkortostan'],
            ['id' => '2985', 'country_id' => '181', 'name' => 'belgorod'],
            ['id' => '2986', 'country_id' => '181', 'name' => 'brjansk'],
            ['id' => '2987', 'country_id' => '181', 'name' => 'burjatija'],
            ['id' => '2988', 'country_id' => '181', 'name' => 'chechenija'],
            ['id' => '2989', 'country_id' => '181', 'name' => 'cheljabinsk'],
            ['id' => '2990', 'country_id' => '181', 'name' => 'chita'],
            ['id' => '2991', 'country_id' => '181', 'name' => 'chukotka'],
            ['id' => '2992', 'country_id' => '181', 'name' => 'chuvashija'],
            ['id' => '2993', 'country_id' => '181', 'name' => 'dagestan'],
            ['id' => '2994', 'country_id' => '181', 'name' => 'evenkija'],
            ['id' => '2995', 'country_id' => '181', 'name' => 'gorno-altaj'],
            ['id' => '2996', 'country_id' => '181', 'name' => 'habarovsk'],
            ['id' => '2997', 'country_id' => '181', 'name' => 'hakasija'],
            ['id' => '2998', 'country_id' => '181', 'name' => 'hanty-mansija'],
            ['id' => '2999', 'country_id' => '181', 'name' => 'ingusetija'],
            ['id' => '3000', 'country_id' => '181', 'name' => 'irkutsk'],
            ['id' => '3001', 'country_id' => '181', 'name' => 'ivanovo'],
            ['id' => '3002', 'country_id' => '181', 'name' => 'jamalo-nenets'],
            ['id' => '3003', 'country_id' => '181', 'name' => 'jaroslavl'],
            ['id' => '3004', 'country_id' => '181', 'name' => 'jevrej'],
            ['id' => '3005', 'country_id' => '181', 'name' => 'kabardino-balkarija'],
            ['id' => '3006', 'country_id' => '181', 'name' => 'kaliningrad'],
            ['id' => '3007', 'country_id' => '181', 'name' => 'kalmykija'],
            ['id' => '3008', 'country_id' => '181', 'name' => 'kaluga'],
            ['id' => '3009', 'country_id' => '181', 'name' => 'kamchatka'],
            ['id' => '3010', 'country_id' => '181', 'name' => 'karachaj-cherkessija'],
            ['id' => '3011', 'country_id' => '181', 'name' => 'karelija'],
            ['id' => '3012', 'country_id' => '181', 'name' => 'kemerovo'],
            ['id' => '3013', 'country_id' => '181', 'name' => 'khabarovskiy kray'],
            ['id' => '3014', 'country_id' => '181', 'name' => 'kirov'],
            ['id' => '3015', 'country_id' => '181', 'name' => 'komi'],
            ['id' => '3016', 'country_id' => '181', 'name' => 'komi-permjakija'],
            ['id' => '3017', 'country_id' => '181', 'name' => 'korjakija'],
            ['id' => '3018', 'country_id' => '181', 'name' => 'kostroma'],
            ['id' => '3019', 'country_id' => '181', 'name' => 'krasnodar'],
            ['id' => '3020', 'country_id' => '181', 'name' => 'krasnojarsk'],
            ['id' => '3021', 'country_id' => '181', 'name' => 'krasnoyarskiy kray'],
            ['id' => '3022', 'country_id' => '181', 'name' => 'kurgan'],
            ['id' => '3023', 'country_id' => '181', 'name' => 'kursk'],
            ['id' => '3024', 'country_id' => '181', 'name' => 'leningrad'],
            ['id' => '3025', 'country_id' => '181', 'name' => 'lipeck'],
            ['id' => '3026', 'country_id' => '181', 'name' => 'magadan'],
            ['id' => '3027', 'country_id' => '181', 'name' => 'marij el'],
            ['id' => '3028', 'country_id' => '181', 'name' => 'mordovija'],
            ['id' => '3029', 'country_id' => '181', 'name' => 'moscow'],
            ['id' => '3030', 'country_id' => '181', 'name' => 'moskovskaja oblast'],
            ['id' => '3031', 'country_id' => '181', 'name' => 'moskovskaya oblast'],
            ['id' => '3032', 'country_id' => '181', 'name' => 'moskva'],
            ['id' => '3033', 'country_id' => '181', 'name' => 'murmansk'],
            ['id' => '3034', 'country_id' => '181', 'name' => 'nenets'],
            ['id' => '3035', 'country_id' => '181', 'name' => 'nizhnij novgorod'],
            ['id' => '3036', 'country_id' => '181', 'name' => 'novgorod'],
            ['id' => '3037', 'country_id' => '181', 'name' => 'novokusnezk'],
            ['id' => '3038', 'country_id' => '181', 'name' => 'novosibirsk'],
            ['id' => '3039', 'country_id' => '181', 'name' => 'omsk'],
            ['id' => '3040', 'country_id' => '181', 'name' => 'orenburg'],
            ['id' => '3041', 'country_id' => '181', 'name' => 'orjol'],
            ['id' => '3042', 'country_id' => '181', 'name' => 'penza'],
            ['id' => '3043', 'country_id' => '181', 'name' => 'perm'],
            ['id' => '3044', 'country_id' => '181', 'name' => 'primorje'],
            ['id' => '3045', 'country_id' => '181', 'name' => 'pskov'],
            ['id' => '3046', 'country_id' => '181', 'name' => 'pskovskaya oblast'],
            ['id' => '3047', 'country_id' => '181', 'name' => 'rjazan'],
            ['id' => '3048', 'country_id' => '181', 'name' => 'rostov'],
            ['id' => '3049', 'country_id' => '181', 'name' => 'saha'],
            ['id' => '3050', 'country_id' => '181', 'name' => 'sahalin'],
            ['id' => '3051', 'country_id' => '181', 'name' => 'samara'],
            ['id' => '3052', 'country_id' => '181', 'name' => 'samarskaya'],
            ['id' => '3053', 'country_id' => '181', 'name' => 'sankt-peterburg'],
            ['id' => '3054', 'country_id' => '181', 'name' => 'saratov'],
            ['id' => '3055', 'country_id' => '181', 'name' => 'smolensk'],
            ['id' => '3056', 'country_id' => '181', 'name' => 'stavropol'],
            ['id' => '3057', 'country_id' => '181', 'name' => 'sverdlovsk'],
            ['id' => '3058', 'country_id' => '181', 'name' => 'tajmyrija'],
            ['id' => '3059', 'country_id' => '181', 'name' => 'tambov'],
            ['id' => '3060', 'country_id' => '181', 'name' => 'tatarstan'],
            ['id' => '3061', 'country_id' => '181', 'name' => 'tjumen'],
            ['id' => '3062', 'country_id' => '181', 'name' => 'tomsk'],
            ['id' => '3063', 'country_id' => '181', 'name' => 'tula'],
            ['id' => '3064', 'country_id' => '181', 'name' => 'tver'],
            ['id' => '3065', 'country_id' => '181', 'name' => 'tyva'],
            ['id' => '3066', 'country_id' => '181', 'name' => 'udmurtija'],
            ['id' => '3067', 'country_id' => '181', 'name' => 'uljanovsk'],
            ['id' => '3068', 'country_id' => '181', 'name' => 'ulyanovskaya oblast'],
            ['id' => '3069', 'country_id' => '181', 'name' => 'ust-orda'],
            ['id' => '3070', 'country_id' => '181', 'name' => 'vladimir'],
            ['id' => '3071', 'country_id' => '181', 'name' => 'volgograd'],
            ['id' => '3072', 'country_id' => '181', 'name' => 'vologda'],
            ['id' => '3073', 'country_id' => '181', 'name' => 'voronezh'],
            ['id' => '3805', 'country_id' => '230', 'name' => 'aberdeen'],
            ['id' => '3806', 'country_id' => '230', 'name' => 'aberdeenshire'],
            ['id' => '3807', 'country_id' => '230', 'name' => 'argyll'],
            ['id' => '3808', 'country_id' => '230', 'name' => 'armagh'],
            ['id' => '3809', 'country_id' => '230', 'name' => 'bedfordshire'],
            ['id' => '3810', 'country_id' => '230', 'name' => 'belfast'],
            ['id' => '3811', 'country_id' => '230', 'name' => 'berkshire'],
            ['id' => '3812', 'country_id' => '230', 'name' => 'birmingham'],
            ['id' => '3813', 'country_id' => '230', 'name' => 'brechin'],
            ['id' => '3814', 'country_id' => '230', 'name' => 'bridgnorth'],
            ['id' => '3815', 'country_id' => '230', 'name' => 'bristol'],
            ['id' => '3816', 'country_id' => '230', 'name' => 'buckinghamshire'],
            ['id' => '3817', 'country_id' => '230', 'name' => 'cambridge'],
            ['id' => '3818', 'country_id' => '230', 'name' => 'cambridgeshire'],
            ['id' => '3819', 'country_id' => '230', 'name' => 'channel islands'],
            ['id' => '3820', 'country_id' => '230', 'name' => 'cheshire'],
            ['id' => '3821', 'country_id' => '230', 'name' => 'cleveland'],
            ['id' => '3822', 'country_id' => '230', 'name' => 'co fermanagh'],
            ['id' => '3823', 'country_id' => '230', 'name' => 'conwy'],
            ['id' => '3824', 'country_id' => '230', 'name' => 'cornwall'],
            ['id' => '3825', 'country_id' => '230', 'name' => 'coventry'],
            ['id' => '3826', 'country_id' => '230', 'name' => 'craven arms'],
            ['id' => '3827', 'country_id' => '230', 'name' => 'cumbria'],
            ['id' => '3828', 'country_id' => '230', 'name' => 'denbighshire'],
            ['id' => '3829', 'country_id' => '230', 'name' => 'derby'],
            ['id' => '3830', 'country_id' => '230', 'name' => 'derbyshire'],
            ['id' => '3831', 'country_id' => '230', 'name' => 'devon'],
            ['id' => '3832', 'country_id' => '230', 'name' => 'dial code dungannon'],
            ['id' => '3833', 'country_id' => '230', 'name' => 'didcot'],
            ['id' => '3834', 'country_id' => '230', 'name' => 'dorset'],
            ['id' => '3835', 'country_id' => '230', 'name' => 'dunbartonshire'],
            ['id' => '3836', 'country_id' => '230', 'name' => 'durham'],
            ['id' => '3837', 'country_id' => '230', 'name' => 'east dunbartonshire'],
            ['id' => '3838', 'country_id' => '230', 'name' => 'east lothian'],
            ['id' => '3839', 'country_id' => '230', 'name' => 'east midlands'],
            ['id' => '3840', 'country_id' => '230', 'name' => 'east sussex'],
            ['id' => '3841', 'country_id' => '230', 'name' => 'east yorkshire'],
            ['id' => '3842', 'country_id' => '230', 'name' => 'england'],
            ['id' => '3843', 'country_id' => '230', 'name' => 'essex'],
            ['id' => '3844', 'country_id' => '230', 'name' => 'fermanagh'],
            ['id' => '3845', 'country_id' => '230', 'name' => 'fife'],
            ['id' => '3846', 'country_id' => '230', 'name' => 'flintshire'],
            ['id' => '3847', 'country_id' => '230', 'name' => 'fulham'],
            ['id' => '3848', 'country_id' => '230', 'name' => 'gainsborough'],
            ['id' => '3849', 'country_id' => '230', 'name' => 'glocestershire'],
            ['id' => '3850', 'country_id' => '230', 'name' => 'gwent'],
            ['id' => '3851', 'country_id' => '230', 'name' => 'hampshire'],
            ['id' => '3852', 'country_id' => '230', 'name' => 'hants'],
            ['id' => '3853', 'country_id' => '230', 'name' => 'herefordshire'],
            ['id' => '3854', 'country_id' => '230', 'name' => 'hertfordshire'],
            ['id' => '3855', 'country_id' => '230', 'name' => 'ireland'],
            ['id' => '3856', 'country_id' => '230', 'name' => 'isle of man'],
            ['id' => '3857', 'country_id' => '230', 'name' => 'isle of wight'],
            ['id' => '3858', 'country_id' => '230', 'name' => 'kenford'],
            ['id' => '3859', 'country_id' => '230', 'name' => 'kent'],
            ['id' => '3860', 'country_id' => '230', 'name' => 'kilmarnock'],
            ['id' => '3861', 'country_id' => '230', 'name' => 'lanarkshire'],
            ['id' => '3862', 'country_id' => '230', 'name' => 'lancashire'],
            ['id' => '3863', 'country_id' => '230', 'name' => 'leicestershire'],
            ['id' => '3864', 'country_id' => '230', 'name' => 'lincolnshire'],
            ['id' => '3865', 'country_id' => '230', 'name' => 'llanymynech'],
            ['id' => '3866', 'country_id' => '230', 'name' => 'london'],
            ['id' => '3867', 'country_id' => '230', 'name' => 'ludlow'],
            ['id' => '3868', 'country_id' => '230', 'name' => 'manchester'],
            ['id' => '3869', 'country_id' => '230', 'name' => 'mayfair'],
            ['id' => '3870', 'country_id' => '230', 'name' => 'merseyside'],
            ['id' => '3871', 'country_id' => '230', 'name' => 'mid glamorgan'],
            ['id' => '3872', 'country_id' => '230', 'name' => 'middlesex'],
            ['id' => '3873', 'country_id' => '230', 'name' => 'mildenhall'],
            ['id' => '3874', 'country_id' => '230', 'name' => 'monmouthshire'],
            ['id' => '3875', 'country_id' => '230', 'name' => 'newton stewart'],
            ['id' => '3876', 'country_id' => '230', 'name' => 'norfolk'],
            ['id' => '3877', 'country_id' => '230', 'name' => 'north humberside'],
            ['id' => '3878', 'country_id' => '230', 'name' => 'north yorkshire'],
            ['id' => '3879', 'country_id' => '230', 'name' => 'northamptonshire'],
            ['id' => '3880', 'country_id' => '230', 'name' => 'northants'],
            ['id' => '3881', 'country_id' => '230', 'name' => 'northern ireland'],
            ['id' => '3882', 'country_id' => '230', 'name' => 'northumberland'],
            ['id' => '3883', 'country_id' => '230', 'name' => 'nottinghamshire'],
            ['id' => '3884', 'country_id' => '230', 'name' => 'oxford'],
            ['id' => '3885', 'country_id' => '230', 'name' => 'powys'],
            ['id' => '3886', 'country_id' => '230', 'name' => 'roos-shire'],
            ['id' => '3887', 'country_id' => '230', 'name' => 'sussex'],
            ['id' => '3888', 'country_id' => '230', 'name' => 'sark'],
            ['id' => '3889', 'country_id' => '230', 'name' => 'scotland'],
            ['id' => '3890', 'country_id' => '230', 'name' => 'scottish borders'],
            ['id' => '3891', 'country_id' => '230', 'name' => 'shropshire'],
            ['id' => '3892', 'country_id' => '230', 'name' => 'somerset'],
            ['id' => '3893', 'country_id' => '230', 'name' => 'south glamorgan'],
            ['id' => '3894', 'country_id' => '230', 'name' => 'south wales'],
            ['id' => '3895', 'country_id' => '230', 'name' => 'south yorkshire'],
            ['id' => '3896', 'country_id' => '230', 'name' => 'southwell'],
            ['id' => '3897', 'country_id' => '230', 'name' => 'staffordshire'],
            ['id' => '3898', 'country_id' => '230', 'name' => 'strabane'],
            ['id' => '3899', 'country_id' => '230', 'name' => 'suffolk'],
            ['id' => '3900', 'country_id' => '230', 'name' => 'surrey'],
            ['id' => '3901', 'country_id' => '230', 'name' => 'sussex'],
            ['id' => '3902', 'country_id' => '230', 'name' => 'twickenham'],
            ['id' => '3903', 'country_id' => '230', 'name' => 'tyne and wear'],
            ['id' => '3904', 'country_id' => '230', 'name' => 'tyrone'],
            ['id' => '3905', 'country_id' => '230', 'name' => 'utah'],
            ['id' => '3906', 'country_id' => '230', 'name' => 'wales'],
            ['id' => '3907', 'country_id' => '230', 'name' => 'warwickshire'],
            ['id' => '3908', 'country_id' => '230', 'name' => 'west lothian'],
            ['id' => '3909', 'country_id' => '230', 'name' => 'west midlands'],
            ['id' => '3910', 'country_id' => '230', 'name' => 'west sussex'],
            ['id' => '3911', 'country_id' => '230', 'name' => 'west yorkshire'],
            ['id' => '3912', 'country_id' => '230', 'name' => 'whissendine'],
            ['id' => '3913', 'country_id' => '230', 'name' => 'wiltshire'],
            ['id' => '3914', 'country_id' => '230', 'name' => 'wokingham'],
            ['id' => '3915', 'country_id' => '230', 'name' => 'worcestershire'],
            ['id' => '3916', 'country_id' => '230', 'name' => 'wrexham'],
            ['id' => '3917', 'country_id' => '230', 'name' => 'wurttemberg'],
            ['id' => '3918', 'country_id' => '230', 'name' => 'yorkshire'],
            ['id' => '3919', 'country_id' => '231', 'name' => 'alabama'],
            ['id' => '3920', 'country_id' => '231', 'name' => 'alaska'],
            ['id' => '3921', 'country_id' => '231', 'name' => 'arizona'],
            ['id' => '3922', 'country_id' => '231', 'name' => 'arkansas'],
            ['id' => '3923', 'country_id' => '231', 'name' => 'byram'],
            ['id' => '3924', 'country_id' => '231', 'name' => 'california'],
            ['id' => '3925', 'country_id' => '231', 'name' => 'cokato'],
            ['id' => '3926', 'country_id' => '231', 'name' => 'colorado'],
            ['id' => '3927', 'country_id' => '231', 'name' => 'connecticut'],
            ['id' => '3928', 'country_id' => '231', 'name' => 'delaware'],
            ['id' => '3929', 'country_id' => '231', 'name' => 'district of columbia'],
            ['id' => '3930', 'country_id' => '231', 'name' => 'florida'],
            ['id' => '3931', 'country_id' => '231', 'name' => 'georgia'],
            ['id' => '3932', 'country_id' => '231', 'name' => 'hawaii'],
            ['id' => '3933', 'country_id' => '231', 'name' => 'idaho'],
            ['id' => '3934', 'country_id' => '231', 'name' => 'illinois'],
            ['id' => '3935', 'country_id' => '231', 'name' => 'indiana'],
            ['id' => '3936', 'country_id' => '231', 'name' => 'iowa'],
            ['id' => '3937', 'country_id' => '231', 'name' => 'kansas'],
            ['id' => '3938', 'country_id' => '231', 'name' => 'kentucky'],
            ['id' => '3939', 'country_id' => '231', 'name' => 'louisiana'],
            ['id' => '3940', 'country_id' => '231', 'name' => 'lowa'],
            ['id' => '3941', 'country_id' => '231', 'name' => 'maine'],
            ['id' => '3942', 'country_id' => '231', 'name' => 'maryland'],
            ['id' => '3943', 'country_id' => '231', 'name' => 'massachusetts'],
            ['id' => '3944', 'country_id' => '231', 'name' => 'medfield'],
            ['id' => '3945', 'country_id' => '231', 'name' => 'michigan'],
            ['id' => '3946', 'country_id' => '231', 'name' => 'minnesota'],
            ['id' => '3947', 'country_id' => '231', 'name' => 'mississippi'],
            ['id' => '3948', 'country_id' => '231', 'name' => 'missouri'],
            ['id' => '3949', 'country_id' => '231', 'name' => 'montana'],
            ['id' => '3950', 'country_id' => '231', 'name' => 'nebraska'],
            ['id' => '3951', 'country_id' => '231', 'name' => 'nevada'],
            ['id' => '3952', 'country_id' => '231', 'name' => 'new hampshire'],
            ['id' => '3953', 'country_id' => '231', 'name' => 'new jersey'],
            ['id' => '3954', 'country_id' => '231', 'name' => 'new jersy'],
            ['id' => '3955', 'country_id' => '231', 'name' => 'new mexico'],
            ['id' => '3956', 'country_id' => '231', 'name' => 'new york'],
            ['id' => '3957', 'country_id' => '231', 'name' => 'north carolina'],
            ['id' => '3958', 'country_id' => '231', 'name' => 'north dakota'],
            ['id' => '3959', 'country_id' => '231', 'name' => 'ohio'],
            ['id' => '3960', 'country_id' => '231', 'name' => 'oklahoma'],
            ['id' => '3961', 'country_id' => '231', 'name' => 'ontario'],
            ['id' => '3962', 'country_id' => '231', 'name' => 'oregon'],
            ['id' => '3963', 'country_id' => '231', 'name' => 'pennsylvania'],
            ['id' => '3964', 'country_id' => '231', 'name' => 'ramey'],
            ['id' => '3965', 'country_id' => '231', 'name' => 'rhode island'],
            ['id' => '3966', 'country_id' => '231', 'name' => 'south carolina'],
            ['id' => '3967', 'country_id' => '231', 'name' => 'south dakota'],
            ['id' => '3968', 'country_id' => '231', 'name' => 'sublimity'],
            ['id' => '3969', 'country_id' => '231', 'name' => 'tennessee'],
            ['id' => '3970', 'country_id' => '231', 'name' => 'texas'],
            ['id' => '3971', 'country_id' => '231', 'name' => 'trimble'],
            ['id' => '3972', 'country_id' => '231', 'name' => 'utah'],
            ['id' => '3973', 'country_id' => '231', 'name' => 'vermont'],
            ['id' => '3974', 'country_id' => '231', 'name' => 'virginia'],
            ['id' => '3975', 'country_id' => '231', 'name' => 'washington'],
            ['id' => '3976', 'country_id' => '231', 'name' => 'west virginia'],
            ['id' => '3977', 'country_id' => '231', 'name' => 'wisconsin'],
            ['id' => '3978', 'country_id' => '231', 'name' => 'wyoming'],
        ];

        foreach ($states as $state) {
            State::factory()->create($state);
        }
    }
}
